# interaction.py
from datetime import datetime

from pydantic import BaseModel, Field


class AskQuestionRequest(BaseModel):
    """
    Data sent when a student asks the AI Teacher a question.
    """

    lesson_id: int | None = None

    student_id: int | None = None

    question: str = Field(
        ...,
        min_length=1,
        max_length=5000,
    )

    language: str = Field(
        default="english",
        max_length=50,
    )


class AnswerRequest(BaseModel):
    """
    Data sent when a student submits an answer
    to a question generated by the AI Teacher.
    """

    question_id: str = Field(
        ...,
        min_length=1,
        max_length=100,
    )

    lesson_id: int | None = None

    student_id: int | None = None

    answer: str = Field(
        ...,
        min_length=1,
        max_length=5000,
    )


class TeacherResponse(BaseModel):
    """
    Response generated by the AI Teacher.
    """

    message: str

    explanation: str | None = None

    feedback: str | None = None

    next_action: str | None = None

    timestamp: datetime | None = None


class InteractionResponse(BaseModel):
    """
    Standard response for student-teacher interactions.
    """

    success: bool

    response: TeacherResponse | None = None

    message: str | None = None